Feature/db usage
SenseNet/sensenet pull request #1321
Opened 2021-02-15 03:03 UTC by kavics

2021-02-18 09:38 UTC, tusmester requested changes

2021-02-18 09:38 UTC, tusmester commented on src/Storage/Data/DataProvider.cs
> +        public abstract void LoadDatabaseUsage(
See below, this should be async.

2021-02-18 09:38 UTC, tusmester commented on src/Storage/DataModel/Usage/DatabaseUsage.cs
> +        public Dimensions System { get; set; }
Add AuditLog info.

2021-02-18 16:57 UTC, kavics commented on src/ContentRepository/DatabaseUsageHandler.cs
> +        private async Task<Node> EnsureFolderAsync(string path, CancellationToken cancel)
The CreateStructure is not async.

2021-02-19 10:20 UTC, tusmester approved these changes

2021-02-19 10:20 UTC, merged